---
title: "17.01.2023"
author: "Tim Kerr"
date: "2023-01-17"
output: html_document
---

# Stan

### Vectors and Declarations

    int x[y];

Means y instances of your variable x if x is \[1,2,3\], y should be 3

    vector[x] y[z]

Means a vector called y, with z columns, and x rows. Or a vector of z instances of x element vectors.

$\left[ \begin{array}{} 1 & 1 & ... & z \\ 2 & 2 & ... & z \\ ... & ... & ... & z\\ x & x & x & x \end{array} \right]$

### Linking choice and value

Value is the internal associative value of a participant. I initially tried to keep the RW model simple, and enforce a 1:1 mapping of value to choice (expectancy ratings). But for the life of me, and after a week invested in Stan, it just wouldn't work. The outputs were identical if I commented out the model section, as when it was active.

It was only when choice is linked via a distribution to value, that it actually works.

Quite why it cant estimate a simple learning rate, without this linking distribtiuon, I do not know. More reading required, perhaps.

The Lei Zhang models all use a softmax (categorical logistic regression), which I didn't see the importance of. This obviously wont apply to scales of 1-9.

Other distributions to try will be normal, and the beta distribution, which allows for more accuracy.

I finally get the reason for the beta distribution!
